// App Layout
export const NAV_MENU_TOGGLE = "NAV_MENU_TOGGLE";
export const THEME_SWITCHER = "THEME_SWITCHER";

// Advice
export const LOAD_ADVICES = "LOAD_ADVICES";
export const EMPTY_ADVICES = "EMPTY_ADVICES";
export const OLDEST_ADVICE = "OLDEST_ADVICE";
export const UPVOTED_ADVICE = "UPVOTED_ADVICE";
export const RECENT_ADVICE = "RECENT_ADVICE";
export const BOOKMARKED_ADVICE = "BOOKMARKED_ADVICE";
